export type QuranFileEntry = {
  number: number;
  fileName: string;
  data: any;
};

export const quranFiles: QuranFileEntry[] = [
  { number: 1, fileName: "001_al-fatiha.json", data: require("../../../data/Quran/001_al-fatiha.json") },
  { number: 2, fileName: "002_al-baqarah.json", data: require("../../../data/Quran/002_al-baqarah.json") },
  { number: 3, fileName: "003_aal-e-imran.json", data: require("../../../data/Quran/003_aal-e-imran.json") },
  { number: 4, fileName: "004_an-nisa.json", data: require("../../../data/Quran/004_an-nisa.json") },
  { number: 5, fileName: "005_al-maidah.json", data: require("../../../data/Quran/005_al-maidah.json") },
  { number: 6, fileName: "006_al-anam.json", data: require("../../../data/Quran/006_al-anam.json") },
  { number: 7, fileName: "007_al-araf.json", data: require("../../../data/Quran/007_al-araf.json") },
  { number: 8, fileName: "008_al-anfal.json", data: require("../../../data/Quran/008_al-anfal.json") },
  { number: 9, fileName: "009_at-tawbah.json", data: require("../../../data/Quran/009_at-tawbah.json") },
  { number: 10, fileName: "010_yunus.json", data: require("../../../data/Quran/010_yunus.json") },
  { number: 11, fileName: "011_hud.json", data: require("../../../data/Quran/011_hud.json") },
  { number: 12, fileName: "012_yusuf.json", data: require("../../../data/Quran/012_yusuf.json") },
  { number: 13, fileName: "013_ar-rad.json", data: require("../../../data/Quran/013_ar-rad.json") },
  { number: 14, fileName: "014_ibrahim.json", data: require("../../../data/Quran/014_ibrahim.json") },
  { number: 15, fileName: "015_al-hijr.json", data: require("../../../data/Quran/015_al-hijr.json") },
  { number: 16, fileName: "016_an-nahl.json", data: require("../../../data/Quran/016_an-nahl.json") },
  { number: 17, fileName: "017_al-isra.json", data: require("../../../data/Quran/017_al-isra.json") },
  { number: 18, fileName: "018_al-kahf.json", data: require("../../../data/Quran/018_al-kahf.json") },
  { number: 19, fileName: "019_maryam.json", data: require("../../../data/Quran/019_maryam.json") },
  { number: 20, fileName: "020_ta-ha.json", data: require("../../../data/Quran/020_ta-ha.json") },
  { number: 21, fileName: "021_al-anbiya.json", data: require("../../../data/Quran/021_al-anbiya.json") },
  { number: 22, fileName: "022_al-hajj.json", data: require("../../../data/Quran/022_al-hajj.json") },
  { number: 23, fileName: "023_al-muminun.json", data: require("../../../data/Quran/023_al-muminun.json") },
  { number: 24, fileName: "024_an-nur.json", data: require("../../../data/Quran/024_an-nur.json") },
  { number: 25, fileName: "025_al-furqan.json", data: require("../../../data/Quran/025_al-furqan.json") },
  { number: 26, fileName: "026_ash-shuara.json", data: require("../../../data/Quran/026_ash-shuara.json") },
  { number: 27, fileName: "027_an-naml.json", data: require("../../../data/Quran/027_an-naml.json") },
  { number: 28, fileName: "028_al-qasas.json", data: require("../../../data/Quran/028_al-qasas.json") },
  { number: 29, fileName: "029_al-ankabut.json", data: require("../../../data/Quran/029_al-ankabut.json") },
  { number: 30, fileName: "030_ar-rum.json", data: require("../../../data/Quran/030_ar-rum.json") },
  { number: 31, fileName: "031_luqman.json", data: require("../../../data/Quran/031_luqman.json") },
  { number: 32, fileName: "032_as-sajdah.json", data: require("../../../data/Quran/032_as-sajdah.json") },
  { number: 33, fileName: "033_al-ahzab.json", data: require("../../../data/Quran/033_al-ahzab.json") },
  { number: 34, fileName: "034_saba.json", data: require("../../../data/Quran/034_saba.json") },
  { number: 35, fileName: "035_fatir.json", data: require("../../../data/Quran/035_fatir.json") },
  { number: 36, fileName: "036_ya-sin.json", data: require("../../../data/Quran/036_ya-sin.json") },
  { number: 37, fileName: "037_as-saffat.json", data: require("../../../data/Quran/037_as-saffat.json") },
  { number: 38, fileName: "038_sad.json", data: require("../../../data/Quran/038_sad.json") },
  { number: 39, fileName: "039_az-zumar.json", data: require("../../../data/Quran/039_az-zumar.json") },
  { number: 40, fileName: "040_ghafir.json", data: require("../../../data/Quran/040_ghafir.json") },
  { number: 41, fileName: "041_fussilat.json", data: require("../../../data/Quran/041_fussilat.json") },
  { number: 42, fileName: "042_ash-shura.json", data: require("../../../data/Quran/042_ash-shura.json") },
  { number: 43, fileName: "043_az-zukhruf.json", data: require("../../../data/Quran/043_az-zukhruf.json") },
  { number: 44, fileName: "044_ad-dukhkhan.json", data: require("../../../data/Quran/044_ad-dukhkhan.json") },
  { number: 45, fileName: "045_al-jathiya.json", data: require("../../../data/Quran/045_al-jathiya.json") },
  { number: 46, fileName: "046_al-ahqaf.json", data: require("../../../data/Quran/046_al-ahqaf.json") },
  { number: 47, fileName: "047_muhammad.json", data: require("../../../data/Quran/047_muhammad.json") },
  { number: 48, fileName: "048_al-fath.json", data: require("../../../data/Quran/048_al-fath.json") },
  { number: 49, fileName: "049_al-hujurat.json", data: require("../../../data/Quran/049_al-hujurat.json") },
  { number: 50, fileName: "050_qaf.json", data: require("../../../data/Quran/050_qaf.json") },
  { number: 51, fileName: "051_adh-dhariyat.json", data: require("../../../data/Quran/051_adh-dhariyat.json") },
  { number: 52, fileName: "052_at-tur.json", data: require("../../../data/Quran/052_at-tur.json") },
  { number: 53, fileName: "053_an-najm.json", data: require("../../../data/Quran/053_an-najm.json") },
  { number: 54, fileName: "054_al-qamar.json", data: require("../../../data/Quran/054_al-qamar.json") },
  { number: 55, fileName: "055_ar-rahman.json", data: require("../../../data/Quran/055_ar-rahman.json") },
  { number: 56, fileName: "056_al-waqiah.json", data: require("../../../data/Quran/056_al-waqiah.json") },
  { number: 57, fileName: "057_al-hadid.json", data: require("../../../data/Quran/057_al-hadid.json") },
  { number: 58, fileName: "058_al-mujadila.json", data: require("../../../data/Quran/058_al-mujadila.json") },
  { number: 59, fileName: "059_al-hashr.json", data: require("../../../data/Quran/059_al-hashr.json") },
  { number: 60, fileName: "060_al-mumtahina.json", data: require("../../../data/Quran/060_al-mumtahina.json") },
  { number: 61, fileName: "061_as-saff.json", data: require("../../../data/Quran/061_as-saff.json") },
  { number: 62, fileName: "062_al-jumuah.json", data: require("../../../data/Quran/062_al-jumuah.json") },
  { number: 63, fileName: "063_al-munafiqoon.json", data: require("../../../data/Quran/063_al-munafiqoon.json") },
  { number: 64, fileName: "064_at-taghabun.json", data: require("../../../data/Quran/064_at-taghabun.json") },
  { number: 65, fileName: "065_at-talaq.json", data: require("../../../data/Quran/065_at-talaq.json") },
  { number: 66, fileName: "066_at-tahrim.json", data: require("../../../data/Quran/066_at-tahrim.json") },
  { number: 67, fileName: "067_al-mulk.json", data: require("../../../data/Quran/067_al-mulk.json") },
  { number: 68, fileName: "068_al-qalam.json", data: require("../../../data/Quran/068_al-qalam.json") },
  { number: 69, fileName: "069_al-haqqah.json", data: require("../../../data/Quran/069_al-haqqah.json") },
  { number: 70, fileName: "070_al-maarij.json", data: require("../../../data/Quran/070_al-maarij.json") },
  { number: 71, fileName: "071_nooh.json", data: require("../../../data/Quran/071_nooh.json") },
  { number: 72, fileName: "072_al-jinn.json", data: require("../../../data/Quran/072_al-jinn.json") },
  { number: 73, fileName: "073_al-muzzammil.json", data: require("../../../data/Quran/073_al-muzzammil.json") },
  { number: 74, fileName: "074_al-muddathir.json", data: require("../../../data/Quran/074_al-muddathir.json") },
  { number: 75, fileName: "075_al-qiyamah.json", data: require("../../../data/Quran/075_al-qiyamah.json") },
  { number: 76, fileName: "076_al-insan.json", data: require("../../../data/Quran/076_al-insan.json") },
  { number: 77, fileName: "077_al-mursalat.json", data: require("../../../data/Quran/077_al-mursalat.json") },
  { number: 78, fileName: "078_an-naba.json", data: require("../../../data/Quran/078_an-naba.json") },
  { number: 79, fileName: "079_an-naziat.json", data: require("../../../data/Quran/079_an-naziat.json") },
  { number: 80, fileName: "080_abasa.json", data: require("../../../data/Quran/080_abasa.json") },
  { number: 81, fileName: "081_at-takwir.json", data: require("../../../data/Quran/081_at-takwir.json") },
  { number: 82, fileName: "082_al-infitar.json", data: require("../../../data/Quran/082_al-infitar.json") },
  { number: 83, fileName: "083_al-mutaffifin.json", data: require("../../../data/Quran/083_al-mutaffifin.json") },
  { number: 84, fileName: "084_al-inshiqaq.json", data: require("../../../data/Quran/084_al-inshiqaq.json") },
  { number: 85, fileName: "085_al-buruj.json", data: require("../../../data/Quran/085_al-buruj.json") },
  { number: 86, fileName: "086_at-tariq.json", data: require("../../../data/Quran/086_at-tariq.json") },
  { number: 87, fileName: "087_al-ala.json", data: require("../../../data/Quran/087_al-ala.json") },
  { number: 88, fileName: "088_al-ghashiyah.json", data: require("../../../data/Quran/088_al-ghashiyah.json") },
  { number: 89, fileName: "089_al-fajr.json", data: require("../../../data/Quran/089_al-fajr.json") },
  { number: 90, fileName: "090_al-balad.json", data: require("../../../data/Quran/090_al-balad.json") },
  { number: 91, fileName: "091_ash-shams.json", data: require("../../../data/Quran/091_ash-shams.json") },
  { number: 92, fileName: "092_al-layl.json", data: require("../../../data/Quran/092_al-layl.json") },
  { number: 93, fileName: "093_ad-duha.json", data: require("../../../data/Quran/093_ad-duha.json") },
  { number: 94, fileName: "094_ash-sharh.json", data: require("../../../data/Quran/094_ash-sharh.json") },
  { number: 95, fileName: "095_at-tin.json", data: require("../../../data/Quran/095_at-tin.json") },
  { number: 96, fileName: "096_al-alaq.json", data: require("../../../data/Quran/096_al-alaq.json") },
  { number: 97, fileName: "097_al-qadr.json", data: require("../../../data/Quran/097_al-qadr.json") },
  { number: 98, fileName: "098_al-bayyina.json", data: require("../../../data/Quran/098_al-bayyina.json") },
  { number: 99, fileName: "099_az-zalzalah.json", data: require("../../../data/Quran/099_az-zalzalah.json") },
  { number: 100, fileName: "100_al-adiyat.json", data: require("../../../data/Quran/100_al-adiyat.json") },
  { number: 101, fileName: "101_al-qariah.json", data: require("../../../data/Quran/101_al-qariah.json") },
  { number: 102, fileName: "102_at-takathur.json", data: require("../../../data/Quran/102_at-takathur.json") },
  { number: 103, fileName: "103_al-asr.json", data: require("../../../data/Quran/103_al-asr.json") },
  { number: 104, fileName: "104_al-humazah.json", data: require("../../../data/Quran/104_al-humazah.json") },
  { number: 105, fileName: "105_al-fil.json", data: require("../../../data/Quran/105_al-fil.json") },
  { number: 106, fileName: "106_quraish.json", data: require("../../../data/Quran/106_quraish.json") },
  { number: 107, fileName: "107_al-maun.json", data: require("../../../data/Quran/107_al-maun.json") },
  { number: 108, fileName: "108_al-kawthar.json", data: require("../../../data/Quran/108_al-kawthar.json") },
  { number: 109, fileName: "109_al-kafirun.json", data: require("../../../data/Quran/109_al-kafirun.json") },
  { number: 110, fileName: "110_an-nasr.json", data: require("../../../data/Quran/110_an-nasr.json") },
  { number: 111, fileName: "111_al-masad.json", data: require("../../../data/Quran/111_al-masad.json") },
  { number: 112, fileName: "112_al-ikhlas.json", data: require("../../../data/Quran/112_al-ikhlas.json") },
  { number: 113, fileName: "113_al-falaq.json", data: require("../../../data/Quran/113_al-falaq.json") },
  { number: 114, fileName: "114_an-nas.json", data: require("../../../data/Quran/114_an-nas.json") },
];

if (__DEV__) {
  const present = new Set(quranFiles.map((f) => f.number));
  const missing = Array.from({ length: 114 }, (_, i) => i + 1).filter((n) => !present.has(n));
  if (missing.length > 0 || quranFiles.length !== 114) {
    console.warn("[Quran] Missing surah files:", missing);
  }
}
